/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Aphorism {
  'id' : bigint,
  'keyThemes' : Array<string>,
  'section' : string,
  'number' : bigint,
  'authenticText' : string,
  'commentary' : string,
}
export interface AphorismInput {
  'id' : [] | [bigint],
  'keyThemes' : Array<string>,
  'section' : string,
  'number' : bigint,
  'authenticText' : string,
  'commentary' : string,
}
export type Difficulty = { 'intermediate' : null } |
  { 'beginner' : null } |
  { 'advanced' : null };
export interface LeaderboardEntry {
  'total' : bigint,
  'displayName' : string,
  'userId' : Principal,
  'difficulty' : Difficulty,
  'score' : bigint,
  'timestamp' : Timestamp,
  'percentage' : number,
}
export type MateriaSource = { 'boericke' : null } |
  { 'allensKeynotes' : null } |
  { 'lotus' : null };
export interface QuizAttempt {
  'total' : bigint,
  'attemptId' : string,
  'userId' : Principal,
  'difficulty' : Difficulty,
  'score' : bigint,
  'timestamp' : Timestamp,
  'timeSecs' : bigint,
}
export interface Remedy {
  'id' : string,
  'keySymptoms' : Array<string>,
  'latinName' : string,
  'physicalSymptoms' : Array<string>,
  'name' : string,
  'description' : string,
  'modalities' : string,
  'mentalPicture' : string,
  'category' : string,
  'clinicalNotes' : string,
}
export interface RemedyProgress {
  'userId' : Principal,
  'lastStudied' : Timestamp,
  'incorrectCount' : bigint,
  'correctCount' : bigint,
  'remedyId' : string,
}
export interface RepertoryEntry {
  'id' : string,
  'description' : string,
  'symptomCategory' : string,
  'symptomName' : string,
  'remedies' : Array<RepertoryRemedy>,
}
export interface RepertoryEntryInput {
  'id' : [] | [string],
  'description' : string,
  'symptomCategory' : string,
  'symptomName' : string,
  'remedies' : Array<RepertoryRemedy>,
}
export interface RepertoryRemedy {
  'remedyName' : string,
  'grade' : bigint,
  'notes' : string,
  'remedyId' : string,
}
export interface SavedCase {
  'id' : string,
  'matchingRemedies' : Array<string>,
  'userId' : string,
  'name' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
  'selectedSymptoms' : Array<string>,
  'clinicalNotes' : string,
}
export interface SourcedRemedy {
  'id' : string,
  'latinName' : string,
  'clinicalUses' : Array<string>,
  'source' : MateriaSource,
  'physicalSymptoms' : Array<string>,
  'name' : string,
  'keynotes' : Array<string>,
  'modalities' : SourcedRemedyModalities,
  'mentalSymptoms' : Array<string>,
  'constitution' : string,
  'remedyId' : string,
}
export interface SourcedRemedyInput {
  'id' : [] | [string],
  'latinName' : string,
  'clinicalUses' : Array<string>,
  'source' : MateriaSource,
  'physicalSymptoms' : Array<string>,
  'name' : string,
  'keynotes' : Array<string>,
  'modalities' : SourcedRemedyModalities,
  'mentalSymptoms' : Array<string>,
  'constitution' : string,
  'remedyId' : string,
}
export interface SourcedRemedyModalities {
  'better' : Array<string>,
  'worse' : Array<string>,
}
export interface SpacedRepCard {
  'lastReviewed' : Timestamp,
  'userId' : Principal,
  'dueDate' : Timestamp,
  'intervalDays' : bigint,
  'remedyId' : string,
  'easeFactor' : number,
  'repetitions' : bigint,
}
export type StudyMode = { 'flashcard' : null } |
  { 'quiz' : null };
export interface StudySession {
  'durationSecs' : bigint,
  'userId' : Principal,
  'mode' : StudyMode,
  'remedyIds' : Array<string>,
  'timestamp' : Timestamp,
  'sessionId' : string,
  'accuracy' : number,
}
export type ThemePreference = { 'dark' : null } |
  { 'light' : null };
export type Time = bigint;
export type Timestamp = bigint;
export interface UserProfile {
  'principal' : Principal,
  'displayName' : string,
  'createdAt' : Timestamp,
  'themePreference' : ThemePreference,
}
export interface UserStats {
  'averageAccuracy' : number,
  'totalSessions' : bigint,
  'totalStudyTimeSecs' : bigint,
}
export interface _SERVICE {
  'adminBulkImportAphorisms' : ActorMethod<[Array<AphorismInput>], bigint>,
  'adminBulkImportRepertoryEntries' : ActorMethod<
    [Array<RepertoryEntryInput>],
    bigint
  >,
  'adminBulkImportSourcedRemedies' : ActorMethod<
    [Array<SourcedRemedyInput>],
    bigint
  >,
  'adminDeleteAphorism' : ActorMethod<[bigint], boolean>,
  'adminDeleteRepertoryEntry' : ActorMethod<[string], boolean>,
  'adminDeleteSourcedRemedy' : ActorMethod<[string], boolean>,
  'adminUpsertAphorism' : ActorMethod<[AphorismInput], bigint>,
  'adminUpsertRepertoryEntry' : ActorMethod<[RepertoryEntryInput], string>,
  'adminUpsertSourcedRemedy' : ActorMethod<[SourcedRemedyInput], string>,
  'bootstrapAdmin' : ActorMethod<[], boolean>,
  'deleteCase' : ActorMethod<[string], boolean>,
  'deleteRemedy' : ActorMethod<[string], undefined>,
  'getAdminList' : ActorMethod<[], Array<Principal>>,
  'getAllCards' : ActorMethod<[], Array<SpacedRepCard>>,
  'getAphorism' : ActorMethod<[bigint], [] | [Aphorism]>,
  'getCaseById' : ActorMethod<[string], [] | [SavedCase]>,
  'getDueCards' : ActorMethod<[], Array<SpacedRepCard>>,
  'getLeaderboard' : ActorMethod<[Difficulty], Array<LeaderboardEntry>>,
  'getMyBookmarks' : ActorMethod<[], Array<string>>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getMyQuizHistory' : ActorMethod<[], Array<QuizAttempt>>,
  'getMyRemedyProgress' : ActorMethod<[], Array<RemedyProgress>>,
  'getMySessions' : ActorMethod<[], Array<StudySession>>,
  'getMyStats' : ActorMethod<[], UserStats>,
  'getRemedy' : ActorMethod<[string], [] | [Remedy]>,
  'getRepertoryEntry' : ActorMethod<[string], [] | [RepertoryEntry]>,
  'getSourcedRemedy' : ActorMethod<[string], [] | [SourcedRemedy]>,
  'grantAdmin' : ActorMethod<[Principal], boolean>,
  'initializeCards' : ActorMethod<[], undefined>,
  'isAdmin' : ActorMethod<[], boolean>,
  'listAphorisms' : ActorMethod<[], Array<Aphorism>>,
  'listMyCases' : ActorMethod<[], Array<SavedCase>>,
  'listRemedies' : ActorMethod<[], Array<Remedy>>,
  'listRepertoryEntries' : ActorMethod<[], Array<RepertoryEntry>>,
  'listSourcedRemedies' : ActorMethod<[], Array<SourcedRemedy>>,
  'listSourcedRemediesBySource' : ActorMethod<
    [MateriaSource],
    Array<SourcedRemedy>
  >,
  'listSourcesByRemedyName' : ActorMethod<[string], Array<SourcedRemedy>>,
  'recordReview' : ActorMethod<[string, bigint], SpacedRepCard>,
  'registerUser' : ActorMethod<[string], undefined>,
  'revokeAdmin' : ActorMethod<[Principal], boolean>,
  'saveCaseAnalysis' : ActorMethod<
    [string, Array<string>, string, Array<string>],
    string
  >,
  'saveQuizAttempt' : ActorMethod<[QuizAttempt], undefined>,
  'saveStudySession' : ActorMethod<[StudySession], undefined>,
  'searchAphorisms' : ActorMethod<[string], Array<Aphorism>>,
  'searchMyCases' : ActorMethod<[string], Array<SavedCase>>,
  'searchRemediesByName' : ActorMethod<[string], Array<Remedy>>,
  'searchRemediesBySymptom' : ActorMethod<[string], Array<Remedy>>,
  'searchRepertory' : ActorMethod<[string], Array<RepertoryEntry>>,
  'seedOrganon' : ActorMethod<[], undefined>,
  'seedRemedies' : ActorMethod<[], undefined>,
  'seedRepertory' : ActorMethod<[], undefined>,
  'seedSourcedRemedies' : ActorMethod<[], undefined>,
  'submitLeaderboardEntry' : ActorMethod<
    [string, bigint, bigint, Difficulty],
    undefined
  >,
  'toggleBookmark' : ActorMethod<[string], undefined>,
  'updateCase' : ActorMethod<[string, string, string], boolean>,
  'updateRemedyProgress' : ActorMethod<[string, boolean], undefined>,
  'upsertRemedy' : ActorMethod<[Remedy], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];