/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Timestamp = IDL.Int;
export const SpacedRepCard = IDL.Record({
  'lastReviewed' : Timestamp,
  'userId' : IDL.Principal,
  'dueDate' : Timestamp,
  'intervalDays' : IDL.Nat,
  'remedyId' : IDL.Text,
  'easeFactor' : IDL.Float64,
  'repetitions' : IDL.Nat,
});
export const Aphorism = IDL.Record({
  'id' : IDL.Nat,
  'keyThemes' : IDL.Vec(IDL.Text),
  'section' : IDL.Text,
  'number' : IDL.Nat,
  'authenticText' : IDL.Text,
  'commentary' : IDL.Text,
});
export const Time = IDL.Int;
export const SavedCase = IDL.Record({
  'id' : IDL.Text,
  'matchingRemedies' : IDL.Vec(IDL.Text),
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
  'selectedSymptoms' : IDL.Vec(IDL.Text),
  'clinicalNotes' : IDL.Text,
});
export const Difficulty = IDL.Variant({
  'intermediate' : IDL.Null,
  'beginner' : IDL.Null,
  'advanced' : IDL.Null,
});
export const LeaderboardEntry = IDL.Record({
  'total' : IDL.Nat,
  'displayName' : IDL.Text,
  'userId' : IDL.Principal,
  'difficulty' : Difficulty,
  'score' : IDL.Nat,
  'timestamp' : Timestamp,
  'percentage' : IDL.Float64,
});
export const ThemePreference = IDL.Variant({
  'dark' : IDL.Null,
  'light' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'createdAt' : Timestamp,
  'themePreference' : ThemePreference,
});
export const QuizAttempt = IDL.Record({
  'total' : IDL.Nat,
  'attemptId' : IDL.Text,
  'userId' : IDL.Principal,
  'difficulty' : Difficulty,
  'score' : IDL.Nat,
  'timestamp' : Timestamp,
  'timeSecs' : IDL.Nat,
});
export const RemedyProgress = IDL.Record({
  'userId' : IDL.Principal,
  'lastStudied' : Timestamp,
  'incorrectCount' : IDL.Nat,
  'correctCount' : IDL.Nat,
  'remedyId' : IDL.Text,
});
export const StudyMode = IDL.Variant({
  'flashcard' : IDL.Null,
  'quiz' : IDL.Null,
});
export const StudySession = IDL.Record({
  'durationSecs' : IDL.Nat,
  'userId' : IDL.Principal,
  'mode' : StudyMode,
  'remedyIds' : IDL.Vec(IDL.Text),
  'timestamp' : Timestamp,
  'sessionId' : IDL.Text,
  'accuracy' : IDL.Float64,
});
export const UserStats = IDL.Record({
  'averageAccuracy' : IDL.Float64,
  'totalSessions' : IDL.Nat,
  'totalStudyTimeSecs' : IDL.Nat,
});
export const Remedy = IDL.Record({
  'id' : IDL.Text,
  'keySymptoms' : IDL.Vec(IDL.Text),
  'latinName' : IDL.Text,
  'physicalSymptoms' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'modalities' : IDL.Text,
  'mentalPicture' : IDL.Text,
  'category' : IDL.Text,
  'clinicalNotes' : IDL.Text,
});
export const RepertoryRemedy = IDL.Record({
  'remedyName' : IDL.Text,
  'grade' : IDL.Nat,
  'notes' : IDL.Text,
  'remedyId' : IDL.Text,
});
export const RepertoryEntry = IDL.Record({
  'id' : IDL.Text,
  'description' : IDL.Text,
  'symptomCategory' : IDL.Text,
  'symptomName' : IDL.Text,
  'remedies' : IDL.Vec(RepertoryRemedy),
});
export const MateriaSource = IDL.Variant({
  'boericke' : IDL.Null,
  'allensKeynotes' : IDL.Null,
  'lotus' : IDL.Null,
});
export const SourcedRemedyModalities = IDL.Record({
  'better' : IDL.Vec(IDL.Text),
  'worse' : IDL.Vec(IDL.Text),
});
export const SourcedRemedy = IDL.Record({
  'id' : IDL.Text,
  'latinName' : IDL.Text,
  'clinicalUses' : IDL.Vec(IDL.Text),
  'source' : MateriaSource,
  'physicalSymptoms' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'keynotes' : IDL.Vec(IDL.Text),
  'modalities' : SourcedRemedyModalities,
  'mentalSymptoms' : IDL.Vec(IDL.Text),
  'constitution' : IDL.Text,
  'remedyId' : IDL.Text,
});

export const idlService = IDL.Service({
  'deleteCase' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteRemedy' : IDL.Func([IDL.Text], [], []),
  'getAllCards' : IDL.Func([], [IDL.Vec(SpacedRepCard)], ['query']),
  'getAphorism' : IDL.Func([IDL.Nat], [IDL.Opt(Aphorism)], ['query']),
  'getCaseById' : IDL.Func([IDL.Text], [IDL.Opt(SavedCase)], ['query']),
  'getDueCards' : IDL.Func([], [IDL.Vec(SpacedRepCard)], ['query']),
  'getLeaderboard' : IDL.Func(
      [Difficulty],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getMyBookmarks' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getMyQuizHistory' : IDL.Func([], [IDL.Vec(QuizAttempt)], ['query']),
  'getMyRemedyProgress' : IDL.Func([], [IDL.Vec(RemedyProgress)], ['query']),
  'getMySessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
  'getMyStats' : IDL.Func([], [UserStats], ['query']),
  'getRemedy' : IDL.Func([IDL.Text], [IDL.Opt(Remedy)], ['query']),
  'getRepertoryEntry' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(RepertoryEntry)],
      ['query'],
    ),
  'getSourcedRemedy' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SourcedRemedy)],
      ['query'],
    ),
  'initializeCards' : IDL.Func([], [], []),
  'listAphorisms' : IDL.Func([], [IDL.Vec(Aphorism)], ['query']),
  'listMyCases' : IDL.Func([], [IDL.Vec(SavedCase)], ['query']),
  'listRemedies' : IDL.Func([], [IDL.Vec(Remedy)], ['query']),
  'listRepertoryEntries' : IDL.Func([], [IDL.Vec(RepertoryEntry)], ['query']),
  'listSourcedRemedies' : IDL.Func([], [IDL.Vec(SourcedRemedy)], ['query']),
  'listSourcedRemediesBySource' : IDL.Func(
      [MateriaSource],
      [IDL.Vec(SourcedRemedy)],
      ['query'],
    ),
  'listSourcesByRemedyName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SourcedRemedy)],
      ['query'],
    ),
  'recordReview' : IDL.Func([IDL.Text, IDL.Nat], [SpacedRepCard], []),
  'registerUser' : IDL.Func([IDL.Text], [], []),
  'saveCaseAnalysis' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'saveQuizAttempt' : IDL.Func([QuizAttempt], [], []),
  'saveStudySession' : IDL.Func([StudySession], [], []),
  'searchAphorisms' : IDL.Func([IDL.Text], [IDL.Vec(Aphorism)], ['query']),
  'searchMyCases' : IDL.Func([IDL.Text], [IDL.Vec(SavedCase)], ['query']),
  'searchRemediesByName' : IDL.Func([IDL.Text], [IDL.Vec(Remedy)], ['query']),
  'searchRemediesBySymptom' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Remedy)],
      ['query'],
    ),
  'searchRepertory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(RepertoryEntry)],
      ['query'],
    ),
  'seedOrganon' : IDL.Func([], [], []),
  'seedRemedies' : IDL.Func([], [], []),
  'seedRepertory' : IDL.Func([], [], []),
  'seedSourcedRemedies' : IDL.Func([], [], []),
  'submitLeaderboardEntry' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, Difficulty],
      [],
      [],
    ),
  'toggleBookmark' : IDL.Func([IDL.Text], [], []),
  'updateCase' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
  'updateRemedyProgress' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'upsertRemedy' : IDL.Func([Remedy], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Timestamp = IDL.Int;
  const SpacedRepCard = IDL.Record({
    'lastReviewed' : Timestamp,
    'userId' : IDL.Principal,
    'dueDate' : Timestamp,
    'intervalDays' : IDL.Nat,
    'remedyId' : IDL.Text,
    'easeFactor' : IDL.Float64,
    'repetitions' : IDL.Nat,
  });
  const Aphorism = IDL.Record({
    'id' : IDL.Nat,
    'keyThemes' : IDL.Vec(IDL.Text),
    'section' : IDL.Text,
    'number' : IDL.Nat,
    'authenticText' : IDL.Text,
    'commentary' : IDL.Text,
  });
  const Time = IDL.Int;
  const SavedCase = IDL.Record({
    'id' : IDL.Text,
    'matchingRemedies' : IDL.Vec(IDL.Text),
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
    'selectedSymptoms' : IDL.Vec(IDL.Text),
    'clinicalNotes' : IDL.Text,
  });
  const Difficulty = IDL.Variant({
    'intermediate' : IDL.Null,
    'beginner' : IDL.Null,
    'advanced' : IDL.Null,
  });
  const LeaderboardEntry = IDL.Record({
    'total' : IDL.Nat,
    'displayName' : IDL.Text,
    'userId' : IDL.Principal,
    'difficulty' : Difficulty,
    'score' : IDL.Nat,
    'timestamp' : Timestamp,
    'percentage' : IDL.Float64,
  });
  const ThemePreference = IDL.Variant({
    'dark' : IDL.Null,
    'light' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'createdAt' : Timestamp,
    'themePreference' : ThemePreference,
  });
  const QuizAttempt = IDL.Record({
    'total' : IDL.Nat,
    'attemptId' : IDL.Text,
    'userId' : IDL.Principal,
    'difficulty' : Difficulty,
    'score' : IDL.Nat,
    'timestamp' : Timestamp,
    'timeSecs' : IDL.Nat,
  });
  const RemedyProgress = IDL.Record({
    'userId' : IDL.Principal,
    'lastStudied' : Timestamp,
    'incorrectCount' : IDL.Nat,
    'correctCount' : IDL.Nat,
    'remedyId' : IDL.Text,
  });
  const StudyMode = IDL.Variant({ 'flashcard' : IDL.Null, 'quiz' : IDL.Null });
  const StudySession = IDL.Record({
    'durationSecs' : IDL.Nat,
    'userId' : IDL.Principal,
    'mode' : StudyMode,
    'remedyIds' : IDL.Vec(IDL.Text),
    'timestamp' : Timestamp,
    'sessionId' : IDL.Text,
    'accuracy' : IDL.Float64,
  });
  const UserStats = IDL.Record({
    'averageAccuracy' : IDL.Float64,
    'totalSessions' : IDL.Nat,
    'totalStudyTimeSecs' : IDL.Nat,
  });
  const Remedy = IDL.Record({
    'id' : IDL.Text,
    'keySymptoms' : IDL.Vec(IDL.Text),
    'latinName' : IDL.Text,
    'physicalSymptoms' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'modalities' : IDL.Text,
    'mentalPicture' : IDL.Text,
    'category' : IDL.Text,
    'clinicalNotes' : IDL.Text,
  });
  const RepertoryRemedy = IDL.Record({
    'remedyName' : IDL.Text,
    'grade' : IDL.Nat,
    'notes' : IDL.Text,
    'remedyId' : IDL.Text,
  });
  const RepertoryEntry = IDL.Record({
    'id' : IDL.Text,
    'description' : IDL.Text,
    'symptomCategory' : IDL.Text,
    'symptomName' : IDL.Text,
    'remedies' : IDL.Vec(RepertoryRemedy),
  });
  const MateriaSource = IDL.Variant({
    'boericke' : IDL.Null,
    'allensKeynotes' : IDL.Null,
    'lotus' : IDL.Null,
  });
  const SourcedRemedyModalities = IDL.Record({
    'better' : IDL.Vec(IDL.Text),
    'worse' : IDL.Vec(IDL.Text),
  });
  const SourcedRemedy = IDL.Record({
    'id' : IDL.Text,
    'latinName' : IDL.Text,
    'clinicalUses' : IDL.Vec(IDL.Text),
    'source' : MateriaSource,
    'physicalSymptoms' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'keynotes' : IDL.Vec(IDL.Text),
    'modalities' : SourcedRemedyModalities,
    'mentalSymptoms' : IDL.Vec(IDL.Text),
    'constitution' : IDL.Text,
    'remedyId' : IDL.Text,
  });
  
  return IDL.Service({
    'deleteCase' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteRemedy' : IDL.Func([IDL.Text], [], []),
    'getAllCards' : IDL.Func([], [IDL.Vec(SpacedRepCard)], ['query']),
    'getAphorism' : IDL.Func([IDL.Nat], [IDL.Opt(Aphorism)], ['query']),
    'getCaseById' : IDL.Func([IDL.Text], [IDL.Opt(SavedCase)], ['query']),
    'getDueCards' : IDL.Func([], [IDL.Vec(SpacedRepCard)], ['query']),
    'getLeaderboard' : IDL.Func(
        [Difficulty],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getMyBookmarks' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getMyQuizHistory' : IDL.Func([], [IDL.Vec(QuizAttempt)], ['query']),
    'getMyRemedyProgress' : IDL.Func([], [IDL.Vec(RemedyProgress)], ['query']),
    'getMySessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
    'getMyStats' : IDL.Func([], [UserStats], ['query']),
    'getRemedy' : IDL.Func([IDL.Text], [IDL.Opt(Remedy)], ['query']),
    'getRepertoryEntry' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(RepertoryEntry)],
        ['query'],
      ),
    'getSourcedRemedy' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SourcedRemedy)],
        ['query'],
      ),
    'initializeCards' : IDL.Func([], [], []),
    'listAphorisms' : IDL.Func([], [IDL.Vec(Aphorism)], ['query']),
    'listMyCases' : IDL.Func([], [IDL.Vec(SavedCase)], ['query']),
    'listRemedies' : IDL.Func([], [IDL.Vec(Remedy)], ['query']),
    'listRepertoryEntries' : IDL.Func([], [IDL.Vec(RepertoryEntry)], ['query']),
    'listSourcedRemedies' : IDL.Func([], [IDL.Vec(SourcedRemedy)], ['query']),
    'listSourcedRemediesBySource' : IDL.Func(
        [MateriaSource],
        [IDL.Vec(SourcedRemedy)],
        ['query'],
      ),
    'listSourcesByRemedyName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SourcedRemedy)],
        ['query'],
      ),
    'recordReview' : IDL.Func([IDL.Text, IDL.Nat], [SpacedRepCard], []),
    'registerUser' : IDL.Func([IDL.Text], [], []),
    'saveCaseAnalysis' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'saveQuizAttempt' : IDL.Func([QuizAttempt], [], []),
    'saveStudySession' : IDL.Func([StudySession], [], []),
    'searchAphorisms' : IDL.Func([IDL.Text], [IDL.Vec(Aphorism)], ['query']),
    'searchMyCases' : IDL.Func([IDL.Text], [IDL.Vec(SavedCase)], ['query']),
    'searchRemediesByName' : IDL.Func([IDL.Text], [IDL.Vec(Remedy)], ['query']),
    'searchRemediesBySymptom' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Remedy)],
        ['query'],
      ),
    'searchRepertory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RepertoryEntry)],
        ['query'],
      ),
    'seedOrganon' : IDL.Func([], [], []),
    'seedRemedies' : IDL.Func([], [], []),
    'seedRepertory' : IDL.Func([], [], []),
    'seedSourcedRemedies' : IDL.Func([], [], []),
    'submitLeaderboardEntry' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, Difficulty],
        [],
        [],
      ),
    'toggleBookmark' : IDL.Func([IDL.Text], [], []),
    'updateCase' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Bool], []),
    'updateRemedyProgress' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'upsertRemedy' : IDL.Func([Remedy], [], []),
  });
};

export const init = ({ IDL }) => { return []; };